# Generated by Django 2.0.1 on 2018-01-09 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('destination', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=4)),
                ('deviation', models.IntegerField(blank=True, null=True)),
                ('subscription', models.TextField()),
                ('compensation', models.TextField()),
                ('companions', models.IntegerField(default=0, verbose_name='Amount of Passengers coming with')),
                ('max_companions', models.IntegerField(default=4, verbose_name='Total amount of extra passengers allowed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
