# Generated by Django 2.0 on 2018-01-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmate', '0005_auto_20180111_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='-', max_length=254),
        ),
    ]
