# Generated by Django 2.0 on 2018-01-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmate', '0006_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
