# Generated by Django 2.0 on 2018-01-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmate', '0008_auto_20180112_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/railmate/default_avatar.png', upload_to='avatar/'),
        ),
    ]
