# Generated by Django 2.0.1 on 2018-01-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmate', '0012_auto_20180114_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='station_list',
            field=models.TextField(default='Eindhoven'),
            preserve_default=False,
        ),
    ]
