# Generated by Django 2.0.1 on 2018-01-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railmate', '0012_fellow_passengers'),
        ('railmate', '0013_trip_station_list'),
    ]

    operations = [
    ]
