# Generated by Django 2.0.1 on 2018-01-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railmate', '0014_merge_20180115_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('destination', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=5)),
            ],
        ),
    ]
